# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Estudio Ruiz - Oficina de Diseño / Design Studio
email: info@estudioruiz.co
description: > # this means to ignore newlines until "baseurl:"
  Ruiz, estudio de diseño establecido en Santiago de Chile por los diseñadores Jordi Casanueva y Pablo Serrano. Actualmente en Ruiz nos enfocamos en branding, diseño digital y dirección de arte, participando en proyectos culturales relacionados a la arquitectura, artes visuales, editoriales y más.
  <br>
  <br>
  Design studio based in Santiago de Chile by the designers Jordi Casanueva and Pablo Serrano. Currently in Ruiz we focus in branding, digital design and art direction, engaging in cultural projects related to architecture, visual art, publishing houses and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://estudioruiz.co" # the base hostname & protocol for your site
instagram_username: estudio_ruiz
ruiz_username: ruiz

# Build settings
markdown: kramdown
